### ISSUE TITLE
Fatar error when install contrib module

### ISSUE THREAD

**Issue by csandanov** [drupal-composer/drupal-composer-project#269]
Composer: `1.4.1 2017-03-10 09:29:45`
PHP: `7.1.3 (cli) (built: Mar 17 2017 22:28:12) ( NTS )`

After the initial installation with:
```bash
$ composer create-project "drupal-composer/drupal-project:8.x-dev" /var/www/html --stability dev --no-interaction
```

I try to install a contrib module `composer require drupal/devel` and get the following error:

```
Using version ^1.0@RC for drupal/devel
./composer.json has been updated
Reading ./composer.json
Loading config file ./composer.json
Executing command (/var/www/html): git branch --no-color --no-abbrev -v
Executing command (/var/www/html): git describe --exact-match --tags
Executing command (/var/www/html): git log --pretty="%H" -n1 HEAD
Executing command (/var/www/html): hg branch
Executing command (/var/www/html): fossil branch list
Executing command (/var/www/html): fossil tag list
Executing command (/var/www/html): svn info --xml
Reading /home/www-data/.composer/composer.json
Loading config file /home/www-data/.composer/composer.json
Reading /var/www/html/vendor/composer/installed.json
Reading /home/www-data/.composer/vendor/composer/installed.json
Loading plugin DrupalComposer\DrupalScaffold\Plugin_composer_tmp0
Loading plugin cweagans\Composer\Patches_composer_tmp1
Loading plugin Composer\Installers\Plugin_composer_tmp2
PHP Warning:  Uncaught ErrorException: require_once(ExtenderManager.php): failed to open stream: No such file or directory in phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php(195) : eval()'d code:16
Stack trace:
#0 phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php(195) : eval()'d code(16): Composer\Util\ErrorHandler::handle(2, 'require_once(Ex...', 'phar:///usr/loc...', 16, Array)
#1 phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php(195) : eval()'d code(16): require_once()
#2 phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php(195): eval()
#3 phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php(261): Composer\Plugin\PluginManager->registerPackage(Object(Composer\Package\CompletePackage))
#4 phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php(76): Composer\Plugin\PluginManager->loadRepository(Object(Composer\Repository\InstalledFilesystemRepository))
#5 phar:///usr/local/bin/composer/src/Composer/Factory.php(377): Com in phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php(195) : eval()'d code on line 16

Warning: Uncaught ErrorException: require_once(ExtenderManager.php): failed to open stream: No such file or directory in phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php(195) : eval()'d code:16
Stack trace:
#0 phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php(195) : eval()'d code(16): Composer\Util\ErrorHandler::handle(2, 'require_once(Ex...', 'phar:///usr/loc...', 16, Array)
#1 phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php(195) : eval()'d code(16): require_once()
#2 phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php(195): eval()
#3 phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php(261): Composer\Plugin\PluginManager->registerPackage(Object(Composer\Package\CompletePackage))
#4 phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php(76): Composer\Plugin\PluginManager->loadRepository(Object(Composer\Repository\InstalledFilesystemRepository))
#5 phar:///usr/local/bin/composer/src/Composer/Factory.php(377): Com in phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php(195) : eval()'d code on line 16
PHP Fatal error:  Unknown: Failed opening required 'ExtenderManager.php' (include_path='.:/usr/local/lib/php') in phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php(195) : eval()'d code on line 16

Fatal error: Unknown: Failed opening required 'ExtenderManager.php' (include_path='.:/usr/local/lib/php') in phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php(195) : eval()'d code on line 16
```

Worked fine a few days ago. Has something changed?

**Comment by webflo** [comment]
Do you know which plugin should provider the ``ExtenderManager.php``?

**Comment by csandanov** [comment]
I have no idea, it's a clean vanilla Drupal 8 installation. Worked OK just a few days ago.

**Comment by webflo** [comment]
I think it its related to drupal console. https://github.com/hechoendrupal/drupal-console-extend-plugin/blob/master/src/ExtenderManager.php

**Comment by webflo** [comment]
@jmolivas Can you look into the issue? Thanks!

**Comment by jmolivas** [comment]
@webflo sure, looking at this in ping  you back in a fews/

**Comment by webflo** [comment]
Fixed with the new release in https://github.com/hechoendrupal/drupal-console-extend-plugin/pull/8 

Thanks!
